apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
data:
  redis_host: "redis-master"
  redis_port: "6379"
  redis_db: "0"
  redis_ssl: "false"
  service_name: "auth-service"
  service_version: "1.0.0"
  debug: "false"
  token_expiry: "900"
  password_min_length: "8"
  max_login_attempts: "5"
  lockout_duration: "300"
  max_workers: "10"
  connection_idle_timeout: "10"
  keepalive_timeout: "10"
  keepalive_interval: "2"
  connection_max_age: "10"
  max_connections: "1000"
  connection_grace_period: "10"
  max_concurrent_streams: "100" 