apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: ${DOCKER_REGISTRY}/auth-service:latest
        ports:
        - containerPort: 50051
        env:
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: auth-service-config
              key: redis_host
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: auth-service-config
              key: redis_port
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: auth-service-secrets
              key: redis_password
        - name: ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: auth-service-secrets
              key: encryption_key
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: auth-service-secrets
              key: secret_key
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          grpc:
            port: 50051
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          grpc:
            port: 50051
          initialDelaySeconds: 15
          periodSeconds: 20
        volumeMounts:
        - name: ssl-certs
          mountPath: /app/secrets
          readOnly: true
      volumes:
      - name: ssl-certs
        secret:
          secretName: auth-service-ssl-certs 