apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app: auth-service
    service: auth
spec:
  selector:
    app: auth-service
  ports:
  - port: 50051
    targetPort: 50051
    protocol: TCP
    name: grpc
  type: ClusterIP 