# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import twilio_service_pb2 as twilio__service__pb2


class TwilioServiceStub(object):
    """---------- Service Definition ----------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendCustomerText = channel.unary_unary(
                '/twilio.TwilioService/SendCustomerText',
                request_serializer=twilio__service__pb2.RAGRequest.SerializeToString,
                response_deserializer=twilio__service__pb2.RAGResponse.FromString,
                )


class TwilioServiceServicer(object):
    """---------- Service Definition ----------

    """

    def SendCustomerText(self, request, context):
        """Twilio calls this when customer says something
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TwilioServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendCustomerText': grpc.unary_unary_rpc_method_handler(
                    servicer.SendCustomerText,
                    request_deserializer=twilio__service__pb2.RAGRequest.FromString,
                    response_serializer=twilio__service__pb2.RAGResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'twilio.TwilioService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TwilioService(object):
    """---------- Service Definition ----------

    """

    @staticmethod
    def SendCustomerText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/twilio.TwilioService/SendCustomerText',
            twilio__service__pb2.RAGRequest.SerializeToString,
            twilio__service__pb2.RAGResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
