# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import auth_service_pb2 as auth__service__pb2


class AuthServiceStub(object):
    """AuthService provides authentication and user management functionality
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/authservice.AuthService/Register',
                request_serializer=auth__service__pb2.RegisterRequest.SerializeToString,
                response_deserializer=auth__service__pb2.AuthResponse.FromString,
                )
        self.Login = channel.unary_unary(
                '/authservice.AuthService/Login',
                request_serializer=auth__service__pb2.LoginRequest.SerializeToString,
                response_deserializer=auth__service__pb2.AuthResponse.FromString,
                )
        self.RefreshToken = channel.unary_unary(
                '/authservice.AuthService/RefreshToken',
                request_serializer=auth__service__pb2.RefreshTokenRequest.SerializeToString,
                response_deserializer=auth__service__pb2.AuthResponse.FromString,
                )
        self.Logout = channel.unary_unary(
                '/authservice.AuthService/Logout',
                request_serializer=auth__service__pb2.LogoutRequest.SerializeToString,
                response_deserializer=auth__service__pb2.LogoutResponse.FromString,
                )
        self.GetUserProfile = channel.unary_unary(
                '/authservice.AuthService/GetUserProfile',
                request_serializer=auth__service__pb2.GetUserRequest.SerializeToString,
                response_deserializer=auth__service__pb2.UserProfileResponse.FromString,
                )
        self.UpdateUserProfile = channel.unary_unary(
                '/authservice.AuthService/UpdateUserProfile',
                request_serializer=auth__service__pb2.UpdateUserRequest.SerializeToString,
                response_deserializer=auth__service__pb2.UserProfileResponse.FromString,
                )
        self.DeleteUser = channel.unary_unary(
                '/authservice.AuthService/DeleteUser',
                request_serializer=auth__service__pb2.DeleteUserRequest.SerializeToString,
                response_deserializer=auth__service__pb2.DeleteUserResponse.FromString,
                )
        self.ValidateToken = channel.unary_unary(
                '/authservice.AuthService/ValidateToken',
                request_serializer=auth__service__pb2.ValidateTokenRequest.SerializeToString,
                response_deserializer=auth__service__pb2.ValidateTokenResponse.FromString,
                )
        self.RevokeToken = channel.unary_unary(
                '/authservice.AuthService/RevokeToken',
                request_serializer=auth__service__pb2.RevokeTokenRequest.SerializeToString,
                response_deserializer=auth__service__pb2.RevokeTokenResponse.FromString,
                )
        self.CheckHealth = channel.unary_unary(
                '/authservice.AuthService/CheckHealth',
                request_serializer=auth__service__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=auth__service__pb2.HealthCheckResponse.FromString,
                )


class AuthServiceServicer(object):
    """AuthService provides authentication and user management functionality
    """

    def Register(self, request, context):
        """Register creates a new user account
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Login authenticates a user and returns access/refresh tokens
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshToken(self, request, context):
        """RefreshToken generates new access and refresh tokens
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Logout invalidates the current session
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserProfile(self, request, context):
        """GetUserProfile retrieves user information
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUserProfile(self, request, context):
        """UpdateUserProfile updates user information
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUser(self, request, context):
        """DeleteUser removes a user account
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateToken(self, request, context):
        """ValidateToken verifies if a token is valid
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeToken(self, request, context):
        """RevokeToken invalidates a specific token
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckHealth(self, request, context):
        """CheckHealth verifies if the service is operational
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=auth__service__pb2.RegisterRequest.FromString,
                    response_serializer=auth__service__pb2.AuthResponse.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=auth__service__pb2.LoginRequest.FromString,
                    response_serializer=auth__service__pb2.AuthResponse.SerializeToString,
            ),
            'RefreshToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshToken,
                    request_deserializer=auth__service__pb2.RefreshTokenRequest.FromString,
                    response_serializer=auth__service__pb2.AuthResponse.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=auth__service__pb2.LogoutRequest.FromString,
                    response_serializer=auth__service__pb2.LogoutResponse.SerializeToString,
            ),
            'GetUserProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserProfile,
                    request_deserializer=auth__service__pb2.GetUserRequest.FromString,
                    response_serializer=auth__service__pb2.UserProfileResponse.SerializeToString,
            ),
            'UpdateUserProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUserProfile,
                    request_deserializer=auth__service__pb2.UpdateUserRequest.FromString,
                    response_serializer=auth__service__pb2.UserProfileResponse.SerializeToString,
            ),
            'DeleteUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUser,
                    request_deserializer=auth__service__pb2.DeleteUserRequest.FromString,
                    response_serializer=auth__service__pb2.DeleteUserResponse.SerializeToString,
            ),
            'ValidateToken': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateToken,
                    request_deserializer=auth__service__pb2.ValidateTokenRequest.FromString,
                    response_serializer=auth__service__pb2.ValidateTokenResponse.SerializeToString,
            ),
            'RevokeToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeToken,
                    request_deserializer=auth__service__pb2.RevokeTokenRequest.FromString,
                    response_serializer=auth__service__pb2.RevokeTokenResponse.SerializeToString,
            ),
            'CheckHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckHealth,
                    request_deserializer=auth__service__pb2.HealthCheckRequest.FromString,
                    response_serializer=auth__service__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'authservice.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AuthService(object):
    """AuthService provides authentication and user management functionality
    """

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/authservice.AuthService/Register',
            auth__service__pb2.RegisterRequest.SerializeToString,
            auth__service__pb2.AuthResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/authservice.AuthService/Login',
            auth__service__pb2.LoginRequest.SerializeToString,
            auth__service__pb2.AuthResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RefreshToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/authservice.AuthService/RefreshToken',
            auth__service__pb2.RefreshTokenRequest.SerializeToString,
            auth__service__pb2.AuthResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/authservice.AuthService/Logout',
            auth__service__pb2.LogoutRequest.SerializeToString,
            auth__service__pb2.LogoutResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUserProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/authservice.AuthService/GetUserProfile',
            auth__service__pb2.GetUserRequest.SerializeToString,
            auth__service__pb2.UserProfileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateUserProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/authservice.AuthService/UpdateUserProfile',
            auth__service__pb2.UpdateUserRequest.SerializeToString,
            auth__service__pb2.UserProfileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/authservice.AuthService/DeleteUser',
            auth__service__pb2.DeleteUserRequest.SerializeToString,
            auth__service__pb2.DeleteUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ValidateToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/authservice.AuthService/ValidateToken',
            auth__service__pb2.ValidateTokenRequest.SerializeToString,
            auth__service__pb2.ValidateTokenResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RevokeToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/authservice.AuthService/RevokeToken',
            auth__service__pb2.RevokeTokenRequest.SerializeToString,
            auth__service__pb2.RevokeTokenResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/authservice.AuthService/CheckHealth',
            auth__service__pb2.HealthCheckRequest.SerializeToString,
            auth__service__pb2.HealthCheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
