apiVersion: v1
kind: Service
metadata:
  name: ollama-service
spec:
  ports:
    - protocol: TCP
      port: 11434
      targetPort: 11434
  type: ClusterIP

---
apiVersion: v1
kind: Endpoints
metadata:
  name: ollama-service
subsets:
  - addresses:
      - ip: 192.168.49.1
    ports:
      - port: 11434