# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: twilio_service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14twilio_service.proto\x12\x06twilio\x1a\x1fgoogle/protobuf/timestamp.proto\"b\n\nRAGRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x15\n\rcustomer_text\x18\x02 \x01(\t\x12)\n\x07history\x18\x03 \x03(\x0b\x32\x18.twilio.ConversationTurn\"a\n\x0bRAGResponse\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0f\n\x07\x61i_text\x18\x02 \x01(\t\x12-\n\ttimestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"]\n\x10\x43onversationTurn\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12-\n\ttimestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\xc9\x01\n\x0b\x43\x61llSession\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x10\n\x08\x63\x61ll_sid\x18\x02 \x01(\t\x12\x13\n\x0b\x66rom_number\x18\x03 \x01(\t\x12\x11\n\tto_number\x18\x04 \x01(\t\x12.\n\nstart_time\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\x08\x65nd_time\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0e\n\x06status\x18\x07 \x01(\t2L\n\rTwilioService\x12;\n\x10SendCustomerText\x12\x12.twilio.RAGRequest\x1a\x13.twilio.RAGResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'twilio_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RAGREQUEST']._serialized_start=65
  _globals['_RAGREQUEST']._serialized_end=163
  _globals['_RAGRESPONSE']._serialized_start=165
  _globals['_RAGRESPONSE']._serialized_end=262
  _globals['_CONVERSATIONTURN']._serialized_start=264
  _globals['_CONVERSATIONTURN']._serialized_end=357
  _globals['_CALLSESSION']._serialized_start=360
  _globals['_CALLSESSION']._serialized_end=561
  _globals['_TWILIOSERVICE']._serialized_start=563
  _globals['_TWILIOSERVICE']._serialized_end=639
# @@protoc_insertion_point(module_scope)
